#!/bin/bash
if [ -z "$(git status --porcelain)" ];then
  echo No uncommited changes detected
else
  echo The following files have uncommited changes:
  git status --porcelain
  echo Refusing to push
  exit 1
fi

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

REMOTE_NAME=$(git config --get branch."$BRANCH_NAME".remote)

if [ -z "$REMOTE_NAME" ]; then
  echo No remote configured for current branch
  echo Refusing to push
  exit 1
fi

LOCAL_VERSION=$(grep -Po '^__version__ = "\K[^"]+' config.py)

REMOTE_VERSION=$(git show "$REMOTE_NAME"/"$BRANCH_NAME":config.py | grep -Po '^__version__ = "\K[^"]+')

if [[ $LOCAL_VERSION == "$REMOTE_VERSION" ]]; then
  echo Version has not been updated
  echo Refusing to push
  exit 1
elif [[ $LOCAL_VERSION == *-dev ]]; then
  echo Version ends with -dev
  echo Refusing to push
  exit 1
elif [[ ! $LOCAL_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo Version must match format: v[0-9]+.[0-9]+.[0-9]+
  echo Refusing to push
  exit 1
else
  echo Version check passed
fi
