[tool.poetry]
name = "firebot"
version = "1.0.0"
description = "A bot that started out as an IRC bot, but is now a lot more"
authors = ["Firepup Sixfifty <firepup650@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
python-dotenv = "^1.0.0"
discord = "^2.7.1"
pylast = "^5.2.0"
pydnsbl = "^1.1.7"
fpsql = "^1, !=1.0.26"

[tool.poetry.dev-dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
